### ISSUE TITLE
Epic: rewrite workspace-images with dazzle v2

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/workspace-images#628]
## Summary

workspace-images are built, combined, and tested using dazzle v2

## Context

[Related internal call](https://www.notion.so/gitpod/workspace-images-is-built-using-dazzle-v2-9c92d993842d4fffa294115aad660e00#16c937ad1ede4ebfb333dca69fe482d0)

## Value

1. It better organizes docker images (instead of labels it uses base and chunk folders)
    1. This will make it easier for the public to contribute
2. It uses buildkit, which'll set us up for [stargazer and lazy pulling](https://github.com/containerd/stargz-snapshotter)
3. Down the road, if creates a path for users to create their own base image, getting off of workspace-full
    1. They would use some chunks from workspace-full, but not depend on an explicit combination from us
4. It'll make ongoing management easier

## Acceptance criteria

- [x] Circle CI workflows are retired
- [x] Github Actions are used for workflows (PR => local, Main => GAR, schedule => Docker Hub)
- [x] Popular images are upgraded to dazzle v2

## Measurement

See a drop in usage of workspace-full:latest use to ~20% of all workspaces within a week

## Hypothesis

If we use dazzle v2, it'll be easier to manage image combinations, allowing us to ship many times a week.

## In scope

https://github.com/gitpod-io/workspace-images/#-images-well-upgrade

https://github.com/gitpod-io/workspace-images/#-images

## Out of scope

https://github.com/gitpod-io/workspace-images/#-no-upgrade-planned

## Complexities

1. Branches used to get built and pushed to Docker, now they are built and tested in a Github Action via a local Docker registry.
2. We use GAR as a private staging repo.

**Comment by kylos101** [comment]
Some additional maintenance work was identified as part of this effort, and tracked in [this new epic](https://github.com/gitpod-io/workspace-images/issues/659).
