### ISSUE TITLE
Epic: Maintenance for workspace-images

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/workspace-images#659]
## Summary

maintenance improvements for workspace-images

## Context

There are a variety of improvements associated with this epic, but, the general theme is to be consistent with other Gitpod repos (main, not master), cover with tests, and lint for errors. Additionally, we should try to use automation to avoid manual work (updating ca-certificates).

## Value

This repo will be more consistent with other Gitpod repos, providing a better developer experience.
Additionally, the linting provided by hadolint-docker will help maintain quality.

## Acceptance criteria

- [ ] https://github.com/gitpod-io/workspace-images/issues/721
- [ ] https://github.com/gitpod-io/workspace-images/issues/614
- [ ] https://github.com/gitpod-io/workspace-images/issues/571
- [ ] https://github.com/gitpod-io/workspace-images/issues/752
- [ ] https://github.com/gitpod-io/workspace-images/issues/643
- [x] https://github.com/gitpod-io/workspace-images/issues/505
- [x] gitpod-io/workspace-images#763

**Comment by kylos101** [comment]
@princerachit well done on this epic, sir. I've removed [the single blocked issue](https://github.com/gitpod-io/workspace-images/issues/759) from it, and will triage myself early this week on next steps.
