### ISSUE TITLE
Epic: Fix auto-fix version upgrade of images

### ISSUE THREAD

**Issue by princerachit** [gitpod-io/workspace-images#661]
### Bug description

The auto-fix bot doesn't work post migration to dazzlev2 images.

### Steps to reproduce

Check the PRs in the PR tab of the repo. The PRs point to legacy images. No new PRs are being created.

### Anything else?

- [x] Make autofix not send updates to `.gitignore`d files: https://github.com/autofix-dev/autofix/issues/13
- [x] Allow repository-local auto-fixers: https://github.com/autofix-dev/autofix/pull/16
- [x] Implement a repository-local auto-fixer for Python variants: https://github.com/gitpod-io/workspace-images/pull/791
- [ ] Implement similar repository-local auto-fixers for all other Dazzle variants

**Comment by princerachit** [comment]
As per the [documentation](https://github.com/autofix-dev/autofix#types-of-bugs-that-can-be-fixed) the versions can be only fixed in the dockerfile. Since we are moving to variants based images, which uses `chunk.yaml`, the bot would not work in its current state.
I would vote to remove the bot integration.

**Comment by princerachit** [comment]
I have closed all the open PRs trying to fix old dockerfiles

**Comment by princerachit** [comment]
@kylos101 I am going to close this issue by tomorrow and remove the bot integration. Let me know if you have any concerns. cc: @jankeromnes

**Comment by jankeromnes** [comment]
Hi @princerachit!

> Check the PRs in the PR tab of the repo. The PRs point to legacy images.

That's because these PRs were created before the dazzlev2 rewrite was merged. Closing them unmerged was the right action. 👍

> No new PRs are being created.

That's because we've [temporarily disabled the automated PRs](https://github.com/autofix-dev/cronjobs/commit/8ef96d1ad551a86f645eaf82c4028f60abfa0eba) to reduce noise during the rewrite (see [discussion on Slack](https://gitpod.slack.com/archives/C01RC164G48/p1642770419041600?thread_ts=1642754481.040600&cid=C01RC164G48) (internal)).

I can re-enable the Pull Requests now to see what the bot finds.

As a reminder, it only sends Pull Requests that are considered absolutely safe to merge (e.g. bump patch or minor versions of tools where it's considered safe, e.g. in order to get critical security updates quickly, but never bump major versions as this carries risk of unexpected breakages -- the rule of thumb for Autofix is "any fix that you'd merge without looking" will open a PR).

> As per the [documentation](https://github.com/autofix-dev/autofix#types-of-bugs-that-can-be-fixed) the versions can be only fixed in the dockerfile. Since we are moving to variants based images, which uses chunk.yaml, the bot would not work in its current state.

That's true, but I think it would be quite easy to make it support `chunk.yaml` as well.

I think disabling the bot entirely would condemn us to having all images bit-rot continuously, and start accumulating public security vulnerabilities until Gitpod becomes extremely unsafe / deprecated / broken over time.

I much prefer the alternative of teaching Autofix how to fix Dazzle's `chunk.yaml`, and I'm happy to do it as it'll probably be a quick fix. 🙂

**Comment by princerachit** [comment]
Thanks for volunteering @jankeromnes . I am assigning this issue to you. Let me know if you need any help in reviewing the changes :)

**Comment by Furisto** [comment]
Hey @jankeromnes, any idea when you will be able to adapt the autofix bot?

**Comment by jankeromnes** [comment]
Hi @Furisto! Thanks for the reminder. Would you be interested in pairing on this?

I think it could be relatively easy to make the autofix bot pick up custom fixers checked into a repository (e.g. under a `.autofix/` directory), and then implement Dazzle-specific fixers to update all the manifests.

**Comment by Furisto** [comment]
@jankeromnes Absolutely! I setup a meeting.

**Comment by jankeromnes** [comment]
Status update:
- [x] Make autofix not send updates to `.gitignore`d files: https://github.com/autofix-dev/autofix/issues/13
- [x] Allow repository-local auto-fixers: https://github.com/autofix-dev/autofix/pull/16
- [ ] Implement a repository-local auto-fixer for Python variants: https://github.com/gitpod-io/workspace-images/pull/790
- [ ] Implement similar repository-local auto-fixers for all other Dazzle variants

**Comment by kylos101** [comment]
@jankeromnes I moved the details from your [comment](https://github.com/gitpod-io/workspace-images/issues/661#issuecomment-1086271886) to this issue's description, and turned the issue into an epic.

**Comment by kylos101** [comment]
@Furisto can you break-down this task (above) `Implement similar repository-local auto-fixers for all other Dazzle variants` into a set of smaller tasks? For example, aside from Python, and Node, what other fixers are you thinking?

**Comment by Furisto** [comment]
@kylos101 Done

**Comment by Furisto** [comment]
@kylos101 Yes, both. The elixir image actually does not specify a version at the moment, so we could get a new version without us realizing. This should be fixed with that task as well.
