### ISSUE TITLE
Use Google Artifact Registry to Cache images and chunks

### ISSUE THREAD

**Issue by princerachit** [gitpod-io/workspace-images#713]
## Current Status
At the moment we are using Github Action's Caching in order to store the generated chunks and images for a branch when a [PR is opened](https://github.com/gitpod-io/workspace-images/blob/b88ed0d2b6a4a0adbf4fdaa9394440327b33d53b/.github/workflows/pull-request.yml#L38-L50).

We also use this caching for the [master branch](https://github.com/gitpod-io/workspace-images/blob/b88ed0d2b6a4a0adbf4fdaa9394440327b33d53b/.github/workflows/push-main.yml#L66-L78).

## Caveats
1. The maximum size of a cache for one repository is [only 10Gi](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy). A few images can take up 10Gi so the cache is never available

## Proposed solution
Instead of using GH Actions Cache, we can use Google Artifact registry to store the images and layers that are produced during build. GAR does not have any restriction on the size of images.

Since we would want to have dedicated images for each PR we can use images with branch suffixes/tags. e.g. `repo-name/workspace-images-<branch>` or `repo-name/workspace-images:<branch>`

For master branch we can do the same except the use of branch name.

We can create another GH action that deletes the temporary images which were generated due to a Pull request.

## Tasks
- [x] Update push-main.yml workflow to make use of GAR as image registry
- [x] #728
- [x] Update pull-request.yml workflow to make use of GAR as image registry
- [ ] <del>Create a merge-pr.yml workflow which deletes the images generated from a PR with branch name <branch-name> </del>
- [x] Create a schedule-pr-reg-clueanup workflow which deletes all the image tag in docker-dev-pr registry which are older than X days
- [ ] <del>#760</del> removed from this issue

**Comment by princerachit** [comment]
Blocked on https://github.com/gitpod-io/workspace-images/issues/741
